language: python

python:
  - "3.4"

install:
  - pip install -r requirements_dev.txt
  - python setup.py develop

script:
  - flake8 crawler test
  - coverage run --source=crawler -m runscript.cli test

after_success:
  coveralls
