language: python

python: 3.5

matrix:
  include:
    - env: TOX_ENV=py35
      python: 3.5
    - env: TOX_ENV=py36
      python: 3.6
  exclude:
    - python: 3.5 # hack to exclude default no-env travis job

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  coveralls
